---
title: "Homework 2"
author: "Xinyi Wang"
date: "9/24/2020"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
```

## Problem 1

```{r}
trashwheel_df = read_xlsx(
  "~/R_columbia/p8105_hw2_xw2758/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet = "Mr. Trash Wheel",
  range = cell_cols("A:N")) %>%
janitor::clean_names() %>%
  drop_na(dumpster) %>%
mutate(
  sports_balls = round(sports_balls),
  sports_balls = as.integer(sports_balls)
)

```

```{r}
precip_2018 = 
  read_excel(
    "~/R_columbia/p8105_hw2_xw2758/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet = "2018 Precipitation",
  skip = 1
  ) %>%
  janitor::clean_names() %>%
    drop_na(month) %>%
    mutate(year=2017) %>%
    relocate(year)
```


Now combine annual precipitation.

```{r}
month_df = 
  tibble(
    month = 1:12,
    month_name = month.name
  ) %>%
precip_df =
  bind_rows(precip_2018, precip_2017) 
left_join(precip_df, month_df, by ="month")
```

This dataset containing information from the Mr. Trashwheel trash collector in Baltimore, Maryland. As trash enters the inner harbor, the trashwheel collects that trash, and stores it in a dumpster. The
